#!/bin/bash

WORK_DIR="$PWD"
OPTIONS_DIR="$WORK_DIR/bin"
OPTIONS=($(ls "$OPTIONS_DIR"/*.sh))

echo "$WORK_DIR" "$OPTIONS_DIR"

# Check if any scripts
[ ${#OPTIONS[@] -eq 0} ] && {

}

usage(){
  echo "Usage: $0 <option>"
  echo "Available options:"
  for opt in "${OPTIONS[@]}"; do
    #opt_name=$(basename ${})
    echo $(basename ${opt%.*})
  done
}

usage
